#ifndef __LANG_H__
#define __LANG_H__

#define MAX_LANG_TEXT 32

typedef struct LANG {
	char name[MAX_LANG_TEXT];

	char LANGUAGE[MAX_LANG_TEXT];
	char SHOW[MAX_LANG_TEXT];
	char HUD[MAX_LANG_TEXT];
	char FPS[MAX_LANG_TEXT];
	char CPU[MAX_LANG_TEXT];
	char CPU_NOTIFICATION[MAX_LANG_TEXT];
	char BATTERY[MAX_LANG_TEXT];
	char TIME[MAX_LANG_TEXT];
	char ORDER[MAX_LANG_TEXT];
	char COMBO_BUTTON[MAX_LANG_TEXT];
	char MENU_BUTTON[MAX_LANG_TEXT];
	char HUD_BUTTON[MAX_LANG_TEXT];
	char SCREENSHOT_BUTTON[MAX_LANG_TEXT];

	char ON[MAX_LANG_TEXT];
	char OFF[MAX_LANG_TEXT];
	char METHOD[MAX_LANG_TEXT];
	char FPS_NUMBER_ONLY[MAX_LANG_TEXT];
	char FPS_PREFIX[MAX_LANG_TEXT];
	char FPS_SUFFIX[MAX_LANG_TEXT];
	char CPU_SPEED[MAX_LANG_TEXT];
	char CPU_BUS_SPEED[MAX_LANG_TEXT];
	char CPU_USAGE[MAX_LANG_TEXT];
	char CPU_SPEED_AND_USAGE[MAX_LANG_TEXT];
	char CPU_BUS_SPEED_AND_USAGE[MAX_LANG_TEXT];
	char PERCENT[MAX_LANG_TEXT];
	char TIME_LEFT[MAX_LANG_TEXT];
	char PERCENT_AND_TIME_LEFT[MAX_LANG_TEXT];
	char TIME_ICON_24H[MAX_LANG_TEXT];
	char TIME_ICON_12H_SUFFIX[MAX_LANG_TEXT];
	char TIME_ICON_12H_NOSUFFIX[MAX_LANG_TEXT];
	char TIME_NOICON_24H[MAX_LANG_TEXT];
	char TIME_NOICON_12H_SUFFIX[MAX_LANG_TEXT];
	char TIME_NOICON_12H_NOSUFFIX[MAX_LANG_TEXT];

	char XMB[MAX_LANG_TEXT];
	char GAME[MAX_LANG_TEXT];
	char POPS[MAX_LANG_TEXT];
	char CLOSE[MAX_LANG_TEXT];
	char ANALOG[MAX_LANG_TEXT];
	char CHANGE_SELECTION[MAX_LANG_TEXT];
	char CHANGE_OPTION[MAX_LANG_TEXT];
	char CHANGE_ALIGNMENT[MAX_LANG_TEXT];
	char CHANGE_ALIGNMENT_FOR_ALL[MAX_LANG_TEXT];
	char CHANGE_CUSTOM_POSITION[MAX_LANG_TEXT];
	char CHANGE_ORDER[MAX_LANG_TEXT];
	char RESET_ORDER[MAX_LANG_TEXT];

	char CTRL_NONE[MAX_LANG_TEXT];
	char CTRL_SELECT[MAX_LANG_TEXT];
	char CTRL_START[MAX_LANG_TEXT];
	char CTRL_UP[MAX_LANG_TEXT];
	char CTRL_RIGHT[MAX_LANG_TEXT];
	char CTRL_DOWN[MAX_LANG_TEXT];
	char CTRL_LEFT[MAX_LANG_TEXT];
	char CTRL_LTRIGGER[MAX_LANG_TEXT];
	char CTRL_RTRIGGER[MAX_LANG_TEXT];
	char CTRL_TRIANGLE[MAX_LANG_TEXT];
	char CTRL_CIRCLE[MAX_LANG_TEXT];
	char CTRL_CROSS[MAX_LANG_TEXT];
	char CTRL_SQUARE[MAX_LANG_TEXT];
	char CTRL_HOME[MAX_LANG_TEXT];
	char CTRL_NOTE[MAX_LANG_TEXT];
	char CTRL_SCREEN[MAX_LANG_TEXT];
	char CTRL_VOLUP[MAX_LANG_TEXT];
	char CTRL_VOLDOWN[MAX_LANG_TEXT];
} LANG;

int loadLang(LANG *lang, int index);

#endif
